
tests:
	python -m doctest pymol-basic-tests.txt
	python -m doctest pymol-regex-tests.txt
	python -m doctest pymol-fst-tests.txt
	python -m doctest pymol-cfg-tests.txt

post:
	cp pymol.py $(HOME)/git/hub/umling/src/umling/
