
tests:
	python -m doctest 01-pymol-basics.txt
	python -m doctest 02-pymol-regex.txt
	python -m doctest pymol-fst-tests.txt
#	python -m doctest pymol-cfg-tests.txt

post:
	cp pymol.py $(HOME)/git/hub/umling/src/umling/
